# File: .github/workflows/workflow.yml
name: eToro GPT Plugin API CI

on:
    push:
        branches:
        - main
    workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: etoro-gpt-plugin-api
  AZURE_WEBAPP_PACKAGE_PATH: 'nest.zip'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.14.0'                # set this to the node version to use

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        # npm run test --if-present
     # working-directory: my-app-path
    - name: Zip files for upload 
      run: zip --symlinks -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} ./*

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Delete zip file
      run: rm ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}



    # - name: Upload artifact for deployment job
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ env.AZURE_WEBAPP_NAME }}
    #     path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#         name: 'Production'
#     steps:
#     - name: 'Deploy to Azure WebApp'
#       uses: azure/webapps-deploy@v2
#       with: 
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
#     - name: Delete zip file
#       run: rm ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}